CREATE SCHEMA `entrevistatecnica` ;
USE entrevistatecnica;


-- Tabla LOCALIDADES
CREATE TABLE LOCALIDADES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    LOCALIDAD VARCHAR(80),
    ACTIVO TINYINT
);

-- Tabla DEPARTAMENTOS
CREATE TABLE DEPARTAMENTOS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DENOMINACION VARCHAR(80),
    LOCALIDAD_ID INT,
    FOREIGN KEY (LOCALIDAD_ID) REFERENCES LOCALIDADES(ID)
);

-- Tabla PUESTOS
CREATE TABLE PUESTOS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    PUESTO VARCHAR(80),
    ACTIVO TINYINT
);

-- Tabla EMPLEADOS
CREATE TABLE EMPLEADOS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    APELLIDO VARCHAR(80),
    NOMBRES VARCHAR(80),
    EDAD INT,
    FECHAALTA DATE,
    SUELDO DOUBLE,
    COMISION DOUBLE,
    DEPARTAMENTO_ID INT,
    PUESTO_ID INT,
    FOREIGN KEY (DEPARTAMENTO_ID) REFERENCES DEPARTAMENTOS(ID),
    FOREIGN KEY (PUESTO_ID) REFERENCES PUESTOS(ID)
);

-- orden correcto de eliminacion
DROP TABLE IF EXISTS EMPLEADOS;
DROP TABLE IF EXISTS DEPARTAMENTOS;
DROP TABLE IF EXISTS PUESTOS;
DROP TABLE IF EXISTS LOCALIDADES;